name: wm-igem
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - sra-tools=3.0.6
  - kraken2=2.1.3
  - bracken=2.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
